# -*- coding: utf-8 -*-
"""test_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xAVNTVPEHaH2eNCAUhLDkXk9PIFKXKWh
"""

from app import add_numbers

def test_addition_correct():
    assert add_numbers(2, 3) == 5